concourse-db:
  image: postgres:9.5
  environment:
    POSTGRES_DB: concourse
    POSTGRES_USER: concourse
    POSTGRES_PASSWORD: changeme
    PGDATA: /database

concourse-web:
  image: concourse/concourse:2.3.1
  links: [concourse-db]
  command: web
  ports: ["8080:8080"]
  volumes: ["./keys/web:/concourse-keys"]
  environment:
    CONCOURSE_BASIC_AUTH_USERNAME: user
    CONCOURSE_BASIC_AUTH_PASSWORD: user
    CONCOURSE_EXTERNAL_URL: http://10.0.2.15:8080
    CONCOURSE_POSTGRES_DATA_SOURCE: |-
      postgres://concourse:changeme@concourse-db:5432/concourse?sslmode=disable

concourse-worker:
  image: concourse/concourse:2.3.1
  privileged: true
  links: [concourse-web]
  entrypoint: ["usr/local/bin/dumb-init","/scripts/run.sh"] 
  volumes: ["./keys/worker:/concourse-keys","./scripts:/scripts"]
  environment:
    CONCOURSE_TSA_HOST: concourse-web
